name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Test
      run: go test -v ./...

  create_release:
    runs-on: ubuntu-latest
    needs: [ test ]
    outputs:
      # This pulls from the CREATE RELEASE step above, referencing it's ID to
      # get its outputs object, which include a `upload_url`. See this blog
      # post for more info:
      # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

  build_linux_amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Build linux/amd64
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -v -o ./neon-linux-amd64 .
    - name: Build linux/arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -v -o ./neon-linux-arm64 .
    - name: Upload neon-linux-amd64
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ jobs.create_release.outputs.upload_url }}
        asset_path: ./neon-linux-amd64
        asset_name: ./neon-linux-amd64
        asset_content_type: application/octet-stream

  build_linux_arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Build linux/arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -v -o ./neon-linux-arm64 .
    - name: Build linux/arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -v -o ./neon-linux-arm64 .
    - name: Upload neon-linux-arm64
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ jobs.create_release.outputs.upload_url }}
        asset_path: ./neon-linux-arm64
        asset_name: ./neon-linux-arm64
        asset_content_type: application/octet-stream
